name: relate_x_front_main
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

assets:
  - assets/fonts/

fonts:
  - family: RobotoMono
    fonts:
      - asset: assets/fonts/RobotoMono-ExtraLightItalic.ttf
        weight: 200
        style: italic
  - family: CourierPrime
    fonts:
      - asset: assets/fonts/CourierPrime/CourierPrime-Regular.ttf
   

    

flutter:
  uses-material-design: true
